spring.application.name=ReadingLog

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

api.security.jwt.secret=${JWT_SECRET_KEY}

api.security.jwt.expiration=${JWT_EXPIRATION}